###############################################################################
# CLKGATE example
#
###############################################################################

ALL_EX  += clkgate.elf

include ../common.mk

all: $(ALL_EX)
all: size

clean:
	$(RM) -r $(BINDIR) $(OBJDIR)

include ../target.mk
