###############################################################################
# UART driver example
#
###############################################################################

ALL_EX  += uart.elf

include ../common.mk

all: $(ALL_EX)
all: size

clean:
	$(RM) -r $(BINDIR) $(OBJDIR)

include ../target.mk