###############################################################################
# AHBSTAT example
#
###############################################################################

ALL_EX  += ahbstat-isr.elf

include ../common.mk

all: $(ALL_EX)
all: size

clean:
	$(RM) -r $(BINDIR) $(OBJDIR)

include ../target.mk
